services:
  - type: web
    name: aviator-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3-dev gcc
      python -m pip install --upgrade pip
      pip install aiohttp==3.8.0 --no-cache-dir --force-reinstall
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    plan: free
