services:
  - type: web
    name: aviator-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3-dev gcc
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
