services:
  - type: web
    name: aviator-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7973528127:AAF-IdHNXlUUHLGgojzjQ2x_MEy2WhP4DIA
    plan: free
