services:
  - type: web
    name: aviator-bot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt --no-cache-dir
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9  # Recommended stable version
    plan: free
